apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: spzftp32f-go 
  janus-idp.io/tekton: spzftp32f-go
  backstage.io/kubernetes-id: spzftp32f-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: spzftp32f-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  